### PR TITLE
User Profile Page #78

### LINKED ISSUE #78: User Profile Page

### PR DESCRIPTION
**Pull request by titiadecastro**

### CODE REVIEW

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
# Feedback: Frontend pretty much finished!!! Good job UwU!!!

---
Request#1: Can u make the update profile bit farther away from form (margin-top)
Request#2: The Profile image dissapears when mobile. I guess that's because of the design. What we can do na lang is to place the image sa taas n lng ng form before all text-inputs!

Screenshot 2021-03-18 at 01 47 13

Thats all really gudd job UwU

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Okii I finished revamping the userStore and it is now possible to edit user information through user model sa server. Now I guess you can create a backend method na to update user infomation sa store and integrate it in the user profile page !!! yehey

anyways to me reviews:
Request#3: change the meta title of user page to showing the username of the user. You can find an example of this sa mga articles, topics, and courses pages.

Screenshot 2021-03-18 at 21 29 38
---
Request#4: integrate the backend and add the other fields.

Here are the fields of the user:
Screenshot 2021-03-19 at 00 04 21

For the year and course, make it similar to the register page but with already the inputted values ng user. 

for the image, if user has no image, display the default picture, else display the picture of the user.

U got thiss @titiadecastro  OwO !!!

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Re-Request#3: change the meta title of user page to showing the username of the user. You can find an example of this sa mga articles, topics, and courses pages.

Screenshot 2021-03-18 at 21 29 38

---

Re-Request#4: Fixed already the backend, finish the profile image.

if user has no image, display the default picture, else display the picture of the user.

---

Request#5: Noticed na ganito ang bitbots sa dashboard, pa fix na lang.
Screenshot 2021-03-21 at 00 40 00

---
Request#6: Idk why the year select is weird here even if my localhost of ur branch is okay naman, can u check what happened to the year select input field.

Screenshot 2021-03-21 at 00 43 56


 
U got disss @titiadecastro OwO !!!

**Comment by nellyXinwei** [comment]
⭐  Fixed UwU ⭐ 
>Re-Request#3: change the meta title of user page to showing the username of the user. You can find an example of this sa mga articles, topics, and courses pages.

>Re-Request#4: Fixed already the backend, finish the profile image.

>Request#6: Idk why the year select is weird here even if my localhost of ur branch is okay naman, can u check what happened to the year select input field.
⭐  Fixed UwU ⭐ 

---

Re-Request#5: [Dashboard] The bitbots have a red border?
Screenshot 2021-03-21 at 00 40 00

Screenshot 2021-03-22 at 04 06 36

---
Request#7: I think your no access modals for the articles dissapeared after u merged from develop. Paayos na lang.

---
Request#8: When User changes picture, can you set it muna even without updating the profile para the user can see how it can look like, or see if the user is able to set the new image without having to update it yet.

---
Request#9: Do you think you can add modals to the user profile page to inform user 
1) similar to your loading modal of logging in, can u make also loading while backend is still updating the user information?
2) Also similar to success log in modal, can you add User information successfully updated modal (no need error modal).

Lezgooowww @titiadecastro OwO !!!

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
⭐  Fixed UwU ⭐ 
>Re-Request#3: change the meta title of user page to showing the username of the user. You can find an example of this sa mga articles, topics, and courses pages.

>Re-Request#4: Fixed already the backend, finish the profile image.

>Request#6: Idk why the year select is weird here even if my localhost of ur branch is okay naman, can u check what happened to the year select input field.
⭐  Fixed UwU ⭐ 

---

Re-Request#5: [Dashboard] The bitbots have a red border?
Screenshot 2021-03-22 at 04 06 36

---
Request#7: I think your no access modals for the articles dissapeared after u merged from develop. Paayos na lang. pa check na lang if you have all the modals u made before guds (desktop and mobile). 

---
Request#8: When User changes picture, can you set it muna even without updating the profile para the user can see how it can look like, or see if the user is able to set the new image without having to update it yet.

---
Request#9: Do you think you can add modals to the user profile page to inform user 
1) similar to your loading modal of logging in, can u make also loading while backend is still updating the user information?
2) Also similar to success log in modal, can you add User information successfully updated modal (no need error modal).

---
⭐  Lezgooowww @titiadecastro OwO !!! ⭐

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
⭐  Fixed UwU ⭐ 

> Request#7: I think your no access modals for the articles dissapeared after u merged from develop. Paayos na lang. pa check na lang if you have all the modals u made before guds (desktop and mobile). 

> Request#8: When User changes picture, can you set it muna even without updating the profile para the user can see how it can look like, or see if the user is able to set the new image without having to update it yet.


> Request#9: Do you think you can add modals to the user profile page to inform user 
>1) similar to your loading modal of logging in, can u make also loading while backend is still updating the user information?
>2) Also similar to success log in modal, can you add User information successfully updated modal (no need error modal).

⭐  Fixed UwU ⭐ 

---

Re-Request#5: [Dashboard] the placement of the bitbots again are not correct again?
Screenshot 2021-03-22 at 14 44 04

---

Request#10: [Discover] Can't scroll down on discover page?
Screenshot 2021-03-22 at 14 45 47

---
⭐  U go @titiadecastro OwO !!! Thx a lot again POWAHHHH ⭐

**Review by njtalba5127 — APPROVED** [review]
⭐  ALLLLLL GUDDDS WETHHH DISSS  UwU  LEZGO @titiadecastro  hhhahah ⭐ 

⭐  Fixed UwU ⭐ 
> Request#10: [Discover] Can't scroll down on discover page?
> Re-Request#5: [Dashboard] the placement of the bitbots again are not correct again?
⭐  Fixed UwU ⭐

**Pull request merged**
