### PR TITLE
About Page #74

### LINKED ISSUE #74: About Page

### PR DESCRIPTION
**Pull request by njtalba5127**

### CODE REVIEW

**Comment by titiadecastro** [comment]
1) the byte logo suddenly goes to the bitbot from widths 767px til 640px

Screen Shot 2021-03-13 at 6 02 28 PM
---
2) can u lessen the margin between these 2? seems a bit inconsistent compared to the hacker/hipster buttons

Screen Shot 2021-03-13 at 5 36 04 PM
--- 
3) there's overflow + can u fix the space between the logo n text?

Screen Shot 2021-03-13 at 5 39 18 PM
---
4) not centered

Screen Shot 2021-03-13 at 6 00 18 PM
---
i think that's it na!

**Review by titiadecastro — CHANGES_REQUESTED** [review]
1) the byte logo suddenly goes to the bitbot from widths 767px til 640px

Screen Shot 2021-03-13 at 6 02 28 PM
---
2) can u lessen the margin between these 2? seems a bit inconsistent compared to the hacker/hipster buttons

Screen Shot 2021-03-13 at 5 36 04 PM
--- 
3) there's overflow + can u fix the space between the logo n text?

Screen Shot 2021-03-13 at 5 39 18 PM
---
4) not centered

Screen Shot 2021-03-13 at 6 00 18 PM
---
i think that's it na!

**Comment by njtalba5127** [comment]
BITBOT VS BYTE LOLLL

**Review by titiadecastro — APPROVED** [review]
this is better!!!! nice one :DD

**Comment by njtalba5127** [comment]
> this is better!!!! nice one :DD

thx @titiadecastro  slr just finished meeting :<< big thx agiannn OwO

**Pull request merged**
