### PR TITLE
Dashboard Page Revamp #44

### LINKED ISSUE #44: Dashboard Revamp

### PR DESCRIPTION
**Pull request by titiadecastro**

### CODE REVIEW

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Request#1: [DESKTOP - TABLET VIEW] Featured Article pa increase na lang ng height size.
Figma (Left) v Yours (Right):
Screenshot 2021-03-07 at 23 51 02

---
Request#2: [MOBILE VIEW] Margin left right to small, make it consistent na lang with your category pages OwO.
Screenshot 2021-03-07 at 23 53 28

---
Request#3: [MOBILE VIEW] Theres a weird padding or margin sa taas ng featured article. pa remove na lang OwO
Screenshot 2021-03-07 at 23 53 50

---
Request#4: Make na lang the layout, arrangement, and text sizes na lang of the text of featured article similar to figma.
Yours:
Screenshot 2021-03-07 at 23 53 59

Figma:
Screenshot 2021-03-08 at 00 00 47

---
Request#5: If there happens to be overflow, use overflow-ellipsis na lang para may "..." when the text overflows. check tailwind docs na lang. U got dis UwU!!!
Screenshot 2021-03-08 at 00 04 12

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Re-Request#4: 
a) Make the margin left and right of the content of featured article smaller na lang similar to the figma design. 
b) Hopefully similar to the design, not truncate the title of the article to only one line. instead, make it show na lang the whole title of the article. The author's name can come down with it na lang, and the description can be shorten naman by overflow ellipsis. the title is more important to be shown fully.

U got this!!!

Yours:
Screenshot 2021-03-08 at 15 00 11


Figma:
Screenshot 2021-03-08 at 00 00 47

---

⭐ FIXED UwU ⭐

>Request#1: [DESKTOP - TABLET VIEW] Featured Article pa increase na lang ng height size.
Figma (Left) v Yours (Right):
Screenshot 2021-03-07 at 23 51 02

> Request#2: [MOBILE VIEW] Margin left right to small, make it consistent na lang with your category pages OwO.
Screenshot 2021-03-07 at 23 53 28

> Request#3: [MOBILE VIEW] Theres a weird padding or margin sa taas ng featured article. pa remove na lang OwO
Screenshot 2021-03-07 at 23 53 50

> Request#5: If there happens to be overflow, use overflow-ellipsis na lang para may "..." when the text overflows. check tailwind docs na lang. U got dis UwU!!!
Screenshot 2021-03-08 at 00 04 12

⭐ FIXED UwU ⭐

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Re-Request#4:
Have more room for the description. the space between the article title + author, and the description of the article too far :/

At least have the description of the article appear around the areas of the box like these screenshots:
Screenshot 2021-03-08 at 20 22 20

Screenshot 2021-03-08 at 20 23 11

 I think it would be better if the text started at the top of that box for [mobile view].

**Comment by titiadecastro** [comment]
> Re-Request#4:
> Have more room for the description. the space between the article title + author, and the description of the article too far :/
> 
> At least have the description of the article appear around the areas of the box like these screenshots:
> Screenshot 2021-03-08 at 20 22 20
> 
> Screenshot 2021-03-08 at 20 23 11
> 
> I think it would be better if the text started at the top of that box for [mobile view].

if i make the position of the description higher, do i still need to shorten the description? since it will have more space naman

**Comment by njtalba5127** [comment]
let the overflow ellipsis handle the trimming of the text!

**Review by njtalba5127 — APPROVED** [review]
⭐ ALL GOODS WITH THIS UwU ⭐

LEZGOO @titiadecastro  :DDDD

**Pull request merged**
