### PR TITLE
Articles Comment System #88

### LINKED ISSUE #88: Articles Comment System

### PR DESCRIPTION
**Pull request by njtalba5127**
Things to Review in this PR/Branch @titiadecastro :
1. The Comment System of the articles
2. Sped up the load time of articles, courses, and topics pages (assuming the store is loaded fully) (Hotfix)
3. Code Blocks of Articles (Hotfix)
4. Design and formatting of articles (Hotfix)
5. value of Search when routing to other pages other than searching leading to discover page will be resetted. (Hotfix)
6. Fixed Entering dashboard Loadtime (hotfix)
7. Landing Page Carousel featured article and courses now connected to store. (hotfix)

### CODE REVIEW

**Review by titiadecastro — CHANGES_REQUESTED** [review]
1. overlap from screen widths 768px until 1279px
Screen Shot 2021-03-24 at 8 57 11 PM
2. size of profile pic from screen widths 768px until 1023px. maybe decrease the width & height nalang or make it a flexbox?
Screen Shot 2021-03-24 at 9 02 17 PM
3. [MOBILE] from screen widths 480px and smaller, there's overlap with the user image and comment text, + the user image cuts
Screen Shot 2021-03-24 at 9 00 07 PM
4. when user has a profile image, it's not rounded?
Screen Shot 2021-03-24 at 9 10 10 PM

**Review by titiadecastro — CHANGES_REQUESTED** [review]
AAA the articles look so nice na :ooo 
1. i noticed lang if there are bullet points, parang nawawala yung padding/margin?
Mobile:
Screen Shot 2021-03-25 at 3 53 24 PM
Screen Shot 2021-03-25 at 3 53 38 PM
Desktop:
Screen Shot 2021-03-25 at 3 56 25 PM

**Comment by njtalba5127** [comment]
> AAA the articles look so nice na :ooo
> 
> 1. i noticed lang if there are bullet points, parang nawawala yung padding/margin?
>    Mobile:
>    Screen Shot 2021-03-25 at 3 53 24 PM
>    Screen Shot 2021-03-25 at 3 53 38 PM
>    Desktop:
>    Screen Shot 2021-03-25 at 3 56 25 PM

ooo hmm, not sure how eh since when i check, markdown parser natin just places it there so cant really edit it

**Review by titiadecastro — CHANGES_REQUESTED** [review]
1. article cards width consistency
dashboard desktop:
Screen Shot 2021-03-25 at 5 37 14 PM
dashboard tablet:
Screen Shot 2021-03-25 at 5 36 57 PM
courses/topics/categories desktop:
Screen Shot 2021-03-25 at 5 38 39 PM

I think thats it! everything else looks fine! :'')

**Review by titiadecastro — APPROVED** [review]
LOOKS GOOD TO ME !! YAAAY

**Pull request merged**
