### PR TITLE
Discover Page

### LINKED ISSUE #50: Discover Page

### PR DESCRIPTION
**Pull request by titiadecastro**

### CODE REVIEW

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Request#1: Can you add a G-link button sa navbar to the discover page (Find navbar sa components). Forgot that I can't route there since router guard TwT.

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Request#2: Font style and weight of "discover" for mobile, pa check na lang the figma (click on discover and at right tab inspect to see the css). 

Screenshot 2021-03-01 at 22 32 51


Request#3: add meta info (you can observe other pages), so that the tab would display the name of the page instead of just ITECH - ITECH.

Screenshot 2021-03-01 at 22 29 58

Request #4: so far kasi we only filter the articles and courses by the name of the category. whe u search for the title of the course or article, the article or course does not due. This is due to our consideration on logic with the computed filtered courses and articles. we didnt consider returning the course if the search value is the same as the names of these courses of articles. 

Screenshot 2021-03-01 at 22 34 30

instead of just return course.categories[0].name.inclues

u can instead create an if statement with or logic for the different cases.

ex:
```javascript
return this.courses.filter(course=>{
if (course.categories[0].name.includes... || course.name.inclues ... || course.topics[0].name.includes ... you get it naman){
return course
}
return ""
}
```

**Comment by njtalba5127** [comment]
Request#5: also can u remove rin the categories button sa nav, some backend issue there if u notice ex if u are for example inside hacker and go to hipster, the state doesn't change. Might have forgotten some logic there sa backend so remove the categories buttons sa nav muna

**Comment by njtalba5127** [comment]
⭐  THX FOR THE REACTIONS TITIA !!! OwO Really loved that engagement :DDD Lezgoo @titiadecastro  UwU ⭐

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
<> FollowUp-Request#2: Font style and weight of "discover" for mobile, pa check na lang the figma (click on discover and at right tab inspect to see the css).

Should be like this from figma:
Screenshot 2021-03-03 at 01 16 18



---

⭐  FIXED UwU ⭐

Request#3: add meta info (you can observe other pages), so that the tab would display the name of the page instead of just ITECH - ITECH.

Request#4: so far kasi we only filter the articles and courses by the name of the category. whe u search for the title of the course or article, the article or course does not due. This is due to our consideration on logic with the computed filtered courses and articles. we didnt consider returning the course if the search value is the same as the names of these courses of articles.

Request#5: also can u remove rin the categories button sa nav, some backend issue there if u notice ex if u are for example inside hacker and go to hipster, the state doesn't change. Might have forgotten some logic there sa backend so remove the categories buttons sa nav muna

⭐ FIXED UwU ⭐

**Comment by njtalba5127** [comment]
Request#6: Add container tailwind class sa discover page for desktop since it looks stretched when it comes to desktop mode.

tho looks good sa mobile na already, you can instead maybe md:container or lg:container for the container class to just apply on those screen sizes (refer to tailwind docs na lang), and not be applied to smaller screens. 

Screenshot 2021-03-03 at 01 24 42

**Comment by titiadecastro** [comment]
@nellyXinwei re: request#2

discover text is bold & looks good on my end :oo is it ok na on urs?

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Request#7: I think you have extra padding sa desktop mode with the container, try to make it the same padding as that of topic / courses / category page.

Screenshot 2021-03-03 at 02 48 50

**Comment by njtalba5127** [comment]
> @nellyXinwei re: request#2
> 
> discover text is bold & looks good on my end :oo is it ok na on urs?

mine still looks like this on my end: 
Screenshot 2021-03-03 at 02 55 32

**Comment by titiadecastro** [comment]
font is bold na :')

**Review by njtalba5127 — APPROVED** [review]
⭐ FIXED Request#7 Margin Consistency, Request#2 Discover Boldening UwU ⭐

**Comment by njtalba5127** [comment]
⭐  All Goods!! LEZGO @titiadecastro  OwO ⭐

**Pull request merged**
