### PR TITLE
Modals #77

### LINKED ISSUE #77: Modals

### PR DESCRIPTION
**Pull request by titiadecastro**

### CODE REVIEW

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
# Feedback: WHAAAAAAA ANG GANDAAAAAA IYUNG LOGINNNNNNNNNN GALINGGGGGGGGG TTwTT huhuhuhuu THX SO MUCH THAT WAS REALLY GUDDDDDD AAAAAA
---
Request#1: The sign out button when on hover, the text becomes black. make it white lng ig.
Screenshot 2021-03-18 at 01 29 50

---
Request#2: Add x button sa logout modal
Request#3: Can u make signout and cancel button be more centered and close to each other?
 
Screenshot 2021-03-18 at 01 31 45

---
Request#4: When signing out, i get the no access to this article modal. I think this is with the router guard. What you can do is to separate the case na lang? have an if for articles, and else if kung dashboard. 

Screenshot 2021-03-18 at 01 33 48

---
Request#5: [MOBILE VIEW] Logout Modal, can you make sign out button above cancel button. sign out button in hierarchy is a more important call to action button . dont forget na lang the x button to close modal i raised in earlier requests :D

Screenshot 2021-03-18 at 01 37 54

**Comment by njtalba5127** [comment]
Request#6: Although not part of the task. parang i noticed na from develop or your user profile pr na maayos naman ang login form ng login page. but then when you go mobile with iphone se sa login for this pr, the submit button gets consumed by the overflow-hidden. can u check if uve changed something sa login ?

Preview from Develop and User Profile Branch:
Screenshot 2021-03-18 at 01 57 30

Preview from this branch (modals): the submit button dissapears :<
Screenshot 2021-03-18 at 01 58 41

---
Request#7: Forgot but did you also add a modal for register page? when user successfully registers?

**Comment by titiadecastro** [comment]
> Request#1: The sign out button when on hover, the text becomes black. make it white lng ig.
> Screenshot 2021-03-18 at 01 29 50

oops the hover change was supposed to be for the background not text HAHAHA WILL FIX IT

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
⭐ FIXED UwU ⭐
> Request#1: The sign out button when on hover, the text becomes black. make it white lng ig.

> Request#2: Add x button sa logout modal

> Request#3: Can u make signout and cancel button be more centered and close to each other?


> Request#4: When signing out, i get the no access to this article modal. I think this is with the router guard. What you can do is to separate the case na lang? have an if for articles, and else if kung dashboard.

> Request#5: [MOBILE VIEW] Logout Modal, can you make sign out button above cancel button. sign out button in hierarchy is a more important call to action button . dont forget na lang the x button to close modal i raised in earlier requests :D
⭐ FIXED UwU ⭐

---
Request#6: [MOBILE] Can u check if the font sizes of the cancel and sign out button have the same font sizes? Cancel button font looks a bit bigger.
Screenshot 2021-03-18 at 20 59 35

When using inspect tool, found out that 14px si signout button
Screenshot 2021-03-18 at 21 01 53

while cancel button is still 16px: as you can see parang walang media query ang font size.
Screenshot 2021-03-18 at 21 03 08

---
Request#7: [MOBILE] can you make the margin between the text and the signout and cancel buttons a bit bigger to separate them a bit more. 

Thats all!!! OwO

**Review by njtalba5127 — APPROVED** [review]
> ⭐ FIXED UwU ⭐
> Request#6: [MOBILE] Can u check if the font sizes of the cancel and sign out button have the same font sizes? Cancel button font looks a bit bigger.

> Request#7: [MOBILE] can you make the margin between the text and the signout and cancel buttons a bit bigger to separate them a bit more.

> ⭐ FIXED UwU ⭐

ALL GUDS WITH DIS UwU!!!

**Pull request merged**
