### PR TITLE
Topics Page Revamp #55

### LINKED ISSUE #55: Topics Page Revamp

### PR DESCRIPTION
**Pull request by titiadecastro**

### CODE REVIEW

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Request#1: Please add back the back buttons, ces didnt really add sa design but it should be the pinaka left of breadcrumb.

Request#2: May error sa build, what happens if you npm run build on terminal? pa post ng screenshot siguro on comment.

**Comment by titiadecastro** [comment]
> Request#2: May error sa build, what happens if you npm run build on terminal? pa post ng screenshot siguro on comment.

Screen Shot 2021-03-05 at 6 25 18 PM

**Comment by njtalba5127** [comment]
> > Request#2: May error sa build, what happens if you npm run build on terminal? pa post ng screenshot siguro on comment.
> 
> Screen Shot 2021-03-05 at 6 25 18 PM

sige ill check this branch out, also the courses

**Comment by njtalba5127** [comment]
Request#3: found the problem @titiadecastro , your breadcrumbs (white circle sa photo) 

Screenshot 2021-03-06 at 00 47 10

 if you look into the orange, you can see that the loader will be loaded if the topic to show is still fetching. else if the page was able to fetch the topic, then it displays the content. (See orange part).

since your breadcrumbs gets data from an undefined while the page is getting the current topic data of the page, the build goes error (tho it works sa development egegegege).

I suggest you place two kinds of breadcrumbs in each if case. 

if topic is null, show only the back button in the breadcrumb.
else above the content, show the whole breadcrumb.

this should be the same problem rin with courses page.

**Comment by titiadecastro** [comment]
fixed na! :^)

**Comment by njtalba5127** [comment]
> fixed na! :^)

hahahah

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Request#4: Is there anything we can do with the weird spacing of the topic name, i think this applies also to courses name. can u try to solve the spacing problem. 

Screenshot 2021-03-06 at 01 30 35

**Comment by njtalba5127** [comment]
Request#5: Same request rin from courses page, please keep the back button when it goes mobile.

**Review by njtalba5127 — APPROVED** [review]
⭐  FIXED!!! ALL GUDS WITH THIS UwU ⭐

**Pull request merged**
