### PR TITLE
Meet The Team Page #87

### LINKED ISSUE #87: Meet The Team Page

### PR DESCRIPTION
**Pull request by titiadecastro**

### CODE REVIEW

**Comment by titiadecastro** [comment]
Screen Shot 2021-03-24 at 12 50 14 AM

.. help why is there an error :oo i tried adding a `v-if="teamCommittees !== null && teamMembers !== null"` but may error parin sa build

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
OOOOO GALENGGG @titiadecastro Lezgowwww!!

Request#1: [Mobile] Inconsistent heights of the cards ex: Aidan's card looks bigger compared to other cards.
Screenshot 2021-03-24 at 17 54 28

---
Request#2: Spacing between each departments. Like this one in the pic. 
Screenshot 2021-03-24 at 17 59 21


ANNDDD DAZZZ PRETTY MUCH ITTT GOOD JOBBBBB OwO ⭐ ⭐ ⭐

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
Re-request#1: [Mobile] Can you make the size and look of the cards similar to figma

Yours:
Screenshot 2021-03-25 at 00 05 18

Figma:
Screenshot 2021-03-25 at 00 02 18

**Review by njtalba5127 — APPROVED** [review]
⭐ ALL GUDS WITH THIS UwU⭐

**Pull request merged**
