### PR TITLE
Titia Hotfix 1

### LINKED ISSUE #95: Titia Hotfix 1
🔥  HOTFIXES 🔥 
1. [FRONTEND] Remove Forgot password buttons
2. [FRONTEND] [FILTER BUTTONS] Selected for Filter Buttons
3. [FRONTEND] MODALS
  - [courses page] [unauth] bookmark button will trigger no access modal for this feature & user will be prompted to log in
4. [FRONTEND] "no matches found" on discover page
5. [FRONTEND] loading placeholders
  - categories
  - topics
  - courses
  - dashboard
  - carousel articles & courses
  - meet the team
  - discover
6. [FRONTEND] [CAROUSEL] bitbots' backgrounds
🔥  HOTFIXES 🔥

### PR DESCRIPTION
**Pull request by titiadecastro**
🔥  Hotfixes 🔥 
1. removed forgot password button in login page
2. selected states for filter buttons in discover
3. unauth carousel placeholders
4. unauth bookmark modal
5. placeholders for courses page 
6. placeholders for category pages
7. animated placeholders for dashboard
8. meet the team placeholders
9. carousel bitbot backgrounds

### CODE REVIEW

**Comment by titiadecastro** [comment]
to review: @nellyXinwei 
1. removed forgot password button in login page
2. selected states for filter buttons in discover
3. unauth carousel placeholders
4. unauth bookmark modal
5. placeholders for courses page (though idk if it's noticeable because it loads so fast na HAHAHAHA)
6. placeholders for category pages
7. animated placeholders for dashboard
8. meet the team placeholders
9. carousel bitbot backgrounds

**Comment by njtalba5127** [comment]
⭐ FIXED UwU ⭐
1. removed forgot password button in login page
2. selected states for filter buttons in discover
3. unauth carousel placeholders
4. unauth bookmark modal
5. placeholders for courses page (though idk if it's noticeable because it loads so fast na HAHAHAHA)
⭐ FIXED UwU ⭐

LEZGOWWWW OwO

**Comment by titiadecastro** [comment]
> 6. placeholders for category pages
> 7. animated placeholders for dashboard
> 8. meet the team placeholders
> 9. carousel bitbot backgrounds

additional things to review! ^^ @nellyXinwei

**Review by njtalba5127 — APPROVED** [review]
⭐ FIXED UwU ⭐
> 6. placeholders for category pages
> 7. animated placeholders for dashboard
> 8. meet the team placeholders
> 9. carousel bitbot backgrounds
⭐ FIXED UwU ⭐

**Pull request merged**
