### PR TITLE
Animations #73

### LINKED ISSUE #73: Animations

### PR DESCRIPTION
**Pull request by titiadecastro**

### CODE REVIEW

**Comment by titiadecastro** [comment]
i like the buttons hahah

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
# Feedback#1: ⭐⭐  YOOOOOO WAWAWWW ANG GANDA NG ARTICLE CARDS WHAHAHHAHAHAH LEZGOOOOOOO (OwO)!!! ⭐ ⭐

---
Request#1: [Unauth Landing Page @carousel] animations rin sa Button cards for courses and articles

---
Request#2: [Dashboard @Featured Article] can u think of animation when users hover, perhaps the picture would zoom in within the card? 

Screenshot 2021-03-11 at 17 08 07

---
Request#3: [Dashboard @Featured Article] Animations for the category cards?

Screenshot 2021-03-11 at 17 08 33

---
Request#4: [Articles Page] Button animations for the comment button, whats next article buttons, bookmark button.

Screenshot 2021-03-11 at 17 10 01

---
Request#5: [Breadcrumbs] perhaps darken the text on hover?

Screenshot 2021-03-11 at 17 11 47

---
Request#6: [The Blue Buttons] Although damnnn those button animations are so cool, parang d bagay for ITECH accoring to ux. they want it more minimalist daw as seen in the design system pages found in figma. 

Screenshot 2021-03-11 at 17 14 57

Figma: 
Screenshot 2021-03-11 at 17 17 49

**Comment by titiadecastro** [comment]
d dashboard bitbots are so cute

**Review by njtalba5127 — CHANGES_REQUESTED** [review]
# Feedback#2: ⭐⭐ LOLLLL CUTE NG BITBOTS HAHWHAHAHA (TwT)!!! REALLY LOVIN THIS UWU ⭐ ⭐

Re-Request#1: [Unauth Landing Page @carousel] Button animation for the cards behind bitbots

Screenshot 2021-03-13 at 00 34 32
---
Re-Request#3: [Dashboard @Featured Article] can u make animations for bitbots a bit faster. love the bitbots huhuhu

---
Re-Request#5: [Breadcrumbs] can u make it such a way na when i select a part of that breadcrumb it would only highlight that part instead of the whole breadcrumb when u hover.

Right now, hovering on any part of the breadcrumb would highlight the whole breadcrumb.

Screenshot 2021-03-13 at 00 33 22

---
Re-Request#6: [The Blue Buttons] the animations are a bit slow on hover, can u make it a bit faster.

Screenshot 2021-03-13 at 00 34 16

---
⭐ FIXED UwU ⭐
> Request#2: [Dashboard @Featured Article] 

> Request#4: [Articles Page] Button animations for the comment button, whats next article buttons, bookmark button.

**Comment by njtalba5127** [comment]
> d dashboard bitbots are so cute

WAAAAA D SO CUTEEE HAHAGAHGAGA

**Comment by titiadecastro** [comment]
> Re-Request#1: [Unauth Landing Page @carousel] Button animation for the cards behind bitbots
> 
> ## Screenshot 2021-03-13 at 00 34 32

there are hover animations na for that! is it not working? or do u mean yung bitbots mismo?

**Comment by titiadecastro** [comment]
oops wait will fix the breadcrumbs again

**Comment by njtalba5127** [comment]
> > Re-Request#1: [Unauth Landing Page @carousel] Button animation for the cards behind bitbots
> > ## Screenshot 2021-03-13 at 00 34 32
> 
> there are hover animations na for that! is it not working? or do u mean yung bitbots mismo?

 WHOOPS NVM GAHAHAHAHA WORKS NAWWW MB AGAHGSS @titiadecastro

**Comment by njtalba5127** [comment]
> oops wait will fix the breadcrumbs again

oyt oyt, if done, change the label from changes requested to review requested @titiadecastro 

do the same for ur other prs rin. for the issues, ill do em na lang UwU

Screenshot 2021-03-13 at 01 30 14

**Comment by titiadecastro** [comment]
are the breadcrumbs working na?

**Review by njtalba5127 — APPROVED** [review]
⭐ ALL GUDS WITH THIS UwU ⭐

**Pull request merged**
